// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPTeoQuGzeldjNZP1k6zHuIQ1Z-GLDIwc',
    appId: '1:703266619276:web:792afd8eac74a594fea0a9',
    messagingSenderId: '703266619276',
    projectId: 'flutter-presence-app-a7303',
    authDomain: 'flutter-presence-app-a7303.firebaseapp.com',
    storageBucket: 'flutter-presence-app-a7303.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQp9pgUPHy7xXJngv7kbtvQzD2nlbFqo',
    appId: '1:703266619276:android:79d459228cc5a2acfea0a9',
    messagingSenderId: '703266619276',
    projectId: 'flutter-presence-app-a7303',
    storageBucket: 'flutter-presence-app-a7303.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCByBkH2L2b-X51jJhO-bNmG6FnHXXPS6g',
    appId: '1:703266619276:ios:dc34025a30368ac7fea0a9',
    messagingSenderId: '703266619276',
    projectId: 'flutter-presence-app-a7303',
    storageBucket: 'flutter-presence-app-a7303.appspot.com',
    iosBundleId: 'com.example.presenceApp',
  );
}
